alias c="clear"
alias nv="nvim"
alias cat="bat"
alias ls="eza --tree --level=2 --icons --color=always --git --group-directories-first"
alias ll="ls -l"
alias la="ls -a"
alias lla="ls -la"
alias kctl="kubectl"
alias ccft="codecrafters"
